---
# Source: nginx-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-release-nginx-chart
  labels:
    helm.sh/chart: nginx-chart-0.1.0
    app.kubernetes.io/name: nginx-chart
    app.kubernetes.io/instance: nginx-release
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
