replicaCount: 2

# Container image
image:
  repository: nginx-custom
  tag: latest
  pullPolicy: IfNotPresent

# Image pull secrets
imagePullSecrets: []

# Override chart name
nameOverride: ""
fullnameOverride: ""

# Service account
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

# Service configuration
service:
  type: NodePort
  port: 80
  nodePort: 30080

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# HTTPRoute (Gateway API)
httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers

# Resources
resources: {}

# Liveness & Readiness probes (додано)
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 3

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Additional volumes and mounts
volumes: []
volumeMounts: []

# Node selector, tolerations, affinity
nodeSelector: {}
tolerations: []
affinity: {}

