apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-release-nginx-chart
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx-chart
        image: nginx-custom:dev

