name: CI/CD NGINX DevOps Task

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонуємо репозиторій
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Логін у GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # 3️⃣ Build Docker image з тегом commit SHA
      - name: Build Docker image
        run: |
          IMAGE_TAG=ghcr.io/sen9jaf/nginx-custom:${GITHUB_SHA::7}
          docker build -t $IMAGE_TAG .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # 4️⃣ Push Docker image
      - name: Push Docker image
        run: docker push $IMAGE_TAG

      # 5️⃣ Встановлення Helm
      - name: Setup Helm
        uses: azure/setup-helm@v3

      # 6️⃣ Деплой через Helm у Kubernetes
      - name: Deploy with Helm
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          helm upgrade --install nginx-release ./nginx-chart \
            --set image.repository=ghcr.io/sen9jaf/nginx-custom \
            --set image.tag=${GITHUB_SHA::7}

